#
# Python SDK for Xooa
#
# Copyright 2018 Xooa
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at:
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License
# for the specific language governing permissions and limitations under the License.
#
# Author: Rahul Kamboj
#
# coding: utf-8


class XooaRequestTimeoutException(Exception):
    """ Xooa Request Timeout Exception received when a synchronous call to the API
    times out and results in a pending response."""

    def __init__(self, result_id, result_url):
        """ Constructor to instantiate XooaRequestTimeoutException

        :param result_id: Result Id returned in Pending Response
        :param result_url: Result Url returned in Pending Response
        """

        super(XooaRequestTimeoutException, self).__init__({'result_id': result_id, 'result_url': result_url})


class XooaApiException(Exception):
    """ Xooa API Exception thrown for any kind of Exception that occurs within the SDK.
    It includes exceptions generated by code and also received from server.
    """

    def __init__(self, error_code, message):
        """ Constructor to instantiate XooaApiException

        :param error_code: Error code indicating the type of error
        :param message: Error message giving the details of the error
        """

        super(XooaApiException, self).__init__({'error_code': error_code, 'error_message': message})


class InvalidParameterException(Exception):
    """ Exception thrown when an input parameter is invalid. """

    def __init__(self):
        super(InvalidParameterException, self).__init__({'error_message': 'Invalid Parameter'})
